modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="spawnvillage"
version="${file.jarVersion}"
displayName="Spawn in Village"
authors="jihuayu"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spawnvillage"
description="Player spawn control"