modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="spawnvillage"
version="${file.jarVersion}"
displayName="Spawn Village"
authors="jihuayu"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spawnvillage"
description="Player spawn control"